name: raya_app
description: Raya — Assistant IA professionnel (app native)
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  dio_cookie_manager: ^3.1.1
  cookie_jar: ^4.0.8
  flutter_secure_storage: ^9.0.0
  flutter_riverpod: ^2.4.9
  flutter_markdown: ^0.6.18
  just_audio: ^0.9.36
  speech_to_text: ^6.6.0
  image_picker: ^1.0.7
  file_picker: ^6.1.1
  device_info_plus: ^9.1.1
  url_launcher: ^6.2.2
  path_provider: ^2.1.1
  local_auth: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
